### ISSUE TITLE
Off-by-one for `f` and `t` motions

### ISSUE THREAD

**Issue by joshbode** [mjl-/vijs#1]
Great idea for the extension! Thank you for sharing this :)

When I use the `f{char}` and `t{char}` motion the position seems to be off-by-one.
For example, with this initial state:
<img width="206" alt="image" src="https://github.com/user-attachments/assets/45ad8e5f-9353-4456-b9c3-860cc7ce23f3">

If I type `ct.` I expect to change up to (but not including) the `.`, but I end up in the following state, which is removing one character too few:
<img width="185" alt="image" src="https://github.com/user-attachments/assets/96ef268f-0a84-4e62-951c-85522422e0be">

Similarly, if I type `cf.` I expect to change to (including) the `.` but I end up in the following state which is also removing one character too few:
<img width="192" alt="image" src="https://github.com/user-attachments/assets/a9086698-faef-443f-a546-aff5a7f91bc7">

Note: Motions `F` and `T` work as I would expect :)

Firefox Version: 131.0.3 (`aarch64`)
Operating System: macOS 15.0.1
Test Site: https://www.w3.org/WAI/UA/TS/html401/cp0101/0101-TEXTAREA.html

**Comment by mjl-** [comment]
@joshbode Thanks for reporting, the old behaviour indeed didn't sense. I think it's fixed with the commit just now, I pushed a new version v0.0.4 to firefox add-ons, should be arriving soon.

I'm curious if there's anything missing that you need. The feature I'm missing most is currently just regular search (with key "/" or "?"), and a "ex" mode (for :%s/xxx/yyy/, etc). Will come in time, but ideally someone beats me to implementing it. (:

**Comment by joshbode** [comment]
Thanks @mjl- - that is working perfectly now :)

I'll have a think about what other features would be good - mostly for me it is the basic motions and editing and they're already supported (thank you :) - now the motions are working as expected I'll be using the plugin more!
